from .dean_serializer import DeanSerializer
from .role_serializer import RoleSerializer
from .director_serializer import DirectorSerializer
from .teacher_serializer import TeacherSerializer
from .student_profile_serializer import StudentProfileSerializer
