from .academic_period_serializer import AcademicPeriodSerializer
from .career_serializer import CareerSerializer
from .classroom_serializer import ClassroomSerializer
from .faculty_serializer import FacultySerializer
from .pensum_serializer import PensumSerializer
from .pensum_subject_serializer import PensumSubjectSerializer
from .school_serializer import SchoolSerializer
from .subject_serializer import SubjectSerializer
