# Generated by Django 4.2.5 on 2023-10-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_deanmodel_user_alter_directormodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='student_id',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
