# Generated by Django 4.0 on 2023-10-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_deanmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='contact_phone',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='identification_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='teachermodel',
            name='teacher_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
