# Generated by Django 4.2.5 on 2023-10-04 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_pensumsubjectmodel_prerequisites'),
        ('accounts', '0004_alter_studentprofilemodel_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofilemodel',
            name='career',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general.careermodel'),
            preserve_default=False,
        ),
    ]
