# Generated by Django 4.0 on 2023-10-27 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0004_alter_teachermodel_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student', to='auth.user'),
        ),
    ]
