# Generated by Django 4.0 on 2023-10-30 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0005_alter_studentprofilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student', to='auth.user'),
        ),
    ]
