# Generated by Django 4.2.5 on 2023-10-06 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofilemodel_career'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deanmodel',
            options={'verbose_name': 'Dean', 'verbose_name_plural': 'Deans'},
        ),
        migrations.AlterModelOptions(
            name='directormodel',
            options={'verbose_name': 'Director', 'verbose_name_plural': 'Directors'},
        ),
        migrations.AlterModelOptions(
            name='rolemodel',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='studentprofilemodel',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='teachermodel',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
    ]
