# Generated by Django 4.2.5 on 2023-10-10 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_pensumsubjectmodel_is_tutoring'),
        ('accounts', '0006_alter_deanmodel_options_alter_directormodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general.schoolmodel'),
            preserve_default=False,
        ),
    ]
