# Generated by Django 4.0 on 2023-10-31 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_studentprofilemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deanmodel',
            name='user',
        ),
    ]
