# Generated by Django 4.0 on 2023-10-31 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_deanmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directormodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='user',
        ),
    ]
