# Generated by Django 4.0 on 2023-11-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_directormodel_user_remove_teachermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='enrollment_status',
            field=models.CharField(choices=[('Enrolled', 'Enrolled'), ('Inactive', 'Inactive'), ('Graduated', 'Graduated')], default='N/A', max_length=20),
        ),
    ]
