# Generated by Django 4.0 on 2023-12-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_studentprofilemodel_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofilemodel',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
