# Generated by Django 4.2.5 on 2023-10-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_directormodel_director_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deanmodel',
            name='dean_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
