# Generated by Django 4.0 on 2023-10-11 04:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensummodel',
            name='end_year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pensummodel',
            name='start_year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
