# Generated by Django 4.2.5 on 2023-10-03 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_academicperiodmodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careermodel',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general.schoolmodel'),
            preserve_default=False,
        ),
    ]
