# Generated by Django 4.0 on 2023-10-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_pensummodel_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensummodel',
            name='version',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
