# Generated by Django 4.2.5 on 2023-10-03 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_careermodel_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensumsubjectmodel',
            name='prerequisites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.pensumsubjectmodel'),
        ),
    ]
