# Generated by Django 4.0 on 2023-10-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_pensummodel_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pensumsubjectmodel',
            name='is_tutoring',
        ),
        migrations.AddField(
            model_name='subjectmodel',
            name='is_tutoring',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
