# Generated by Django 4.2.5 on 2023-10-06 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_alter_pensumsubjectmodel_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectmodel',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='subjectmodel',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
