# Generated by Django 4.0 on 2023-10-17 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_remove_pensumsubjectmodel_is_tutoring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensumsubjectmodel',
            name='prerequisites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pensum_subjects_prerequisites', to='general.subjectmodel'),
        ),
    ]
