# Generated by Django 4.0 on 2023-10-27 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_alter_pensumsubjectmodel_prerequisites'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityRuleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_of_credit_tutoring', models.PositiveIntegerField(default=0)),
                ('max_of_sub_tutoring', models.PositiveIntegerField(default=0)),
                ('max_student_become_special', models.PositiveIntegerField(default=0)),
                ('min_student_secc', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'University Rule',
                'verbose_name_plural': 'University Rules',
            },
        ),
    ]
