# Generated by Django 4.2.5 on 2023-10-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_alter_academicperiodmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensummodel',
            name='end_year',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pensummodel',
            name='start_year',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
