# Generated by Django 4.2.5 on 2023-10-06 03:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_alter_pensummodel_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensummodel',
            name='start_year',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
