# Generated by Django 4.0 on 2023-10-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_academicperiodmodel_next_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universityrulemodel',
            old_name='max_of_sub_tutoring',
            new_name='max_by_sub_tutoring',
        ),
        migrations.AddField(
            model_name='universityrulemodel',
            name='q_of_subj_tutoring',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
