# Generated by Django 4.0 on 2023-10-27 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_rename_max_of_sub_tutoring_universityrulemodel_max_by_sub_tutoring_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universityrulemodel',
            old_name='max_student_become_special',
            new_name='min_student_become_special',
        ),
    ]
