# Generated by Django 4.2.5 on 2023-10-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_alter_pensummodel_end_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensumsubjectmodel',
            name='is_tutoring',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
