# Generated by Django 4.2.5 on 2023-10-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_pensumsubjectmodel_is_tutoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
