# Generated by Django 4.2.5 on 2023-10-10 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_deanmodel_dean_id'),
        ('general', '0011_alter_facultymodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymodel',
            name='dean',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculties', to='accounts.deanmodel'),
        ),
    ]
