# Generated by Django 4.0 on 2023-11-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmodel',
            name='request_n',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
