# Generated by Django 4.0 on 2023-10-11 03:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secc', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('approved', 'Approved'), ('failed', 'Failed'), ('due', 'Due'), ('ongoing', 'Ongoing')], default='active', max_length=10)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.academicperiodmodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.subjectmodel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.teachermodel')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='ScheduleClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=200)),
                ('h_start', models.DateTimeField()),
                ('h_end', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('approved', 'Approved'), ('failed', 'Failed'), ('due', 'Due'), ('ongoing', 'Ongoing')], default='active', max_length=10)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.classmodel')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.classroommodel')),
            ],
            options={
                'verbose_name': 'Schedule Class',
                'verbose_name_plural': 'Schedule Classes',
            },
        ),
        migrations.CreateModel(
            name='SubjectStudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('approved', 'Approved'), ('failed', 'Failed'), ('due', 'Due'), ('ongoing', 'Ongoing')], default='due', max_length=10)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.studentprofilemodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.subjectmodel')),
            ],
            options={
                'verbose_name': 'Subject Student',
                'verbose_name_plural': 'Subject Students',
            },
        ),
        migrations.CreateModel(
            name='ScheduleStudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('approved', 'Approved'), ('failed', 'Failed'), ('due', 'Due'), ('ongoing', 'Ongoing')], default='active', max_length=10)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.scheduleclassmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.studentprofilemodel')),
            ],
            options={
                'verbose_name': 'Schedule Student',
                'verbose_name_plural': 'Schedule Students',
            },
        ),
        migrations.CreateModel(
            name='CareerStudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('approved', 'Approved'), ('failed', 'Failed'), ('due', 'Due'), ('ongoing', 'Ongoing')], default='active', max_length=10)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.careermodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.studentprofilemodel')),
            ],
            options={
                'verbose_name': 'Career Student',
                'verbose_name_plural': 'Career Students',
            },
        ),
    ]
