# Generated by Django 4.2.5 on 2023-09-27 04:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
        ('accounts', '0003_alter_deanmodel_user_alter_directormodel_user_and_more'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectStudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.studentprofilemodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.subjectmodel')),
            ],
        ),
    ]
