# Generated by Django 4.0 on 2023-10-30 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_studentprofilemodel_user'),
        ('catalog', '0002_alter_scheduleclassmodel_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.teachermodel'),
        ),
    ]
