# Generated by Django 4.2.5 on 2023-09-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_subjectstudentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerstudentmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('approved', 'Approved'), ('failed', 'Failed'), ('due', 'Due'), ('ongoing', 'Ongoing')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('approved', 'Approved'), ('failed', 'Failed'), ('due', 'Due'), ('ongoing', 'Ongoing')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduleclassmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('approved', 'Approved'), ('failed', 'Failed'), ('due', 'Due'), ('ongoing', 'Ongoing')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='schedulestudentmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('approved', 'Approved'), ('failed', 'Failed'), ('due', 'Due'), ('ongoing', 'Ongoing')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='subjectstudentmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('approved', 'Approved'), ('failed', 'Failed'), ('due', 'Due'), ('ongoing', 'Ongoing')], default='due', max_length=10),
        ),
    ]
