# Generated by Django 4.0 on 2023-10-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_classmodel_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('approved', 'Approved'), ('failed', 'Failed'), ('due', 'Due'), ('ongoing', 'Ongoing')], default='due', max_length=10),
        ),
    ]
