# Generated by Django 4.2.5 on 2023-10-05 02:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_studentprofilemodel_career'),
        ('general', '0004_alter_pensumsubjectmodel_prerequisites'),
        ('catalog', '0004_remove_classmodel_period_remove_classmodel_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectStudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('approved', 'Approved'), ('failed', 'Failed'), ('due', 'Due'), ('ongoing', 'Ongoing')], default='due', max_length=10)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.studentprofilemodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.subjectmodel')),
            ],
        ),
    ]
