# Generated by Django 4.0 on 2023-10-30 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_studentprofilemodel_user'),
        ('general', '0010_alter_pensumsubjectmodel_pensum'),
        ('catalog', '0006_alter_subjectstudentmodel_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectstudentmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_student', to='accounts.studentprofilemodel'),
        ),
        migrations.AlterField(
            model_name='subjectstudentmodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_student', to='general.subjectmodel'),
        ),
    ]
