# Generated by Django 4.2.5 on 2023-10-06 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_classmodel_scheduleclassmodel_schedulestudentmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerstudentmodel',
            options={'verbose_name': 'Career Student', 'verbose_name_plural': 'Career Students'},
        ),
        migrations.AlterModelOptions(
            name='classmodel',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='scheduleclassmodel',
            options={'verbose_name': 'Schedule Class', 'verbose_name_plural': 'Schedule Classes'},
        ),
        migrations.AlterModelOptions(
            name='schedulestudentmodel',
            options={'verbose_name': 'Schedule Student', 'verbose_name_plural': 'Schedule Students'},
        ),
        migrations.AlterModelOptions(
            name='subjectstudentmodel',
            options={'verbose_name': 'Subject Student', 'verbose_name_plural': 'Subject Students'},
        ),
    ]
