# Generated by Django 4.0 on 2023-11-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_subjectstudentmodel_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleclassmodel',
            name='h_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='scheduleclassmodel',
            name='h_start',
            field=models.TimeField(),
        ),
    ]
