# Generated by Django 4.2.5 on 2023-10-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_careerstudentmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmodel',
            name='secc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleclassmodel',
            name='day',
            field=models.CharField(max_length=200),
        ),
    ]
