# Generated by Django 4.0 on 2023-11-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_scheduleclassmodel_h_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='is_tutoring_now',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
