# Generated by Django 4.0 on 2023-11-30 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_classmodel_is_tutoring_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleclassmodel',
            name='_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='catalog.classmodel'),
        ),
    ]
