# Generated by Django 4.2.5 on 2023-09-21 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequesttutoringModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=180, unique=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('denied', 'Denied'), ('accepted', 'Accepted')], default='pending', max_length=30)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.careermodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.subjectmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verify_requests_t', to=settings.AUTH_USER_MODEL)),
                ('user_verified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_verified_t', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestSeccModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(max_length=180, unique=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('denied', 'Denied'), ('accepted', 'Accepted')], default='pending', max_length=30)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.careermodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='general.subjectmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verify_requests_s', to=settings.AUTH_USER_MODEL)),
                ('user_verified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_verified_s', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
