# Generated by Django 4.0 on 2023-10-27 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_academicperiodmodel_next_period'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttutoringmodel',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='general.academicperiodmodel'),
            preserve_default=False,
        ),
    ]
