# Generated by Django 4.0 on 2023-10-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_requesttutoringmodel_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttutoringmodel',
            name='is_special_course',
            field=models.BooleanField(default=False),
        ),
    ]
