# Generated by Django 4.2.5 on 2023-10-06 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_requestseccmodel_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestseccmodel',
            options={'verbose_name': 'Request Secc', 'verbose_name_plural': 'Request Secc'},
        ),
        migrations.AlterModelOptions(
            name='requesttutoringmodel',
            options={'verbose_name': 'Request tutoring', 'verbose_name_plural': 'Request tutorings'},
        ),
    ]
