# Generated by Django 4.0 on 2023-10-30 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_requesttutoringmodel_is_special_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttutoringmodel',
            name='reason',
        ),
    ]
