# Generated by Django 4.0 on 2023-10-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_requesttutoringmodel_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttutoringmodel',
            name='request_number',
            field=models.CharField(blank=True, max_length=180, unique=True),
        ),
    ]
